name: possumwood
version: '0.1+git'
summary: Possumwood is a graph-based procedural authoring sandbox.
description: |
  Possumwood is a graph-based procedural authoring tool, in concept not dissimilar to popular CG
  packages like Houdini, Blender or Maya. It is intended to serve as a sandbox for computer graphics
  algorithms and libraries, providing a user-friendly and coding-free UI for libraries that would
  otherwise be inaccessible for an average user.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots
base: core18
architectures:
  - build-on: amd64
    run-on: amd64

build-packages:
  - gcc
  - libc6-dev
  - libboost-filesystem1.65-dev
  - libboost-serialization1.65-dev
  - libboost-regex1.65-dev
  - libboost-thread1.65-dev
  - libboost-test1.65-dev
  - libboost-system1.65-dev
  - libboost-program-options1.65-dev
  - libopenexr-dev
  - libqt5opengl5-dev
  - freeglut3-dev
  - libgmp-dev
  - libmpfr-dev
  - libeigen3-dev
  - libxi-dev
  - libxmu-dev
  - libluabind-dev
  - libglew-dev
  - libglfw3-dev
  - libpng-dev
  - libtbb-dev
  - software-properties-common
  - dirmngr

apps:
  possumwood:
    command: desktop-launch possumwood
    plugs: [opengl, home, desktop, gsettings, wayland, x11]
    environment:
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/x86_64-linux-gnu/blas:$SNAP/usr/lib/x86_64-linux-gnu/lapack

  run-bash:
    command: desktop-launch bash
    plugs: [opengl, home, desktop, gsettings, wayland, x11]

plugs:
  gtk-3-themes:
    interface: content
    target: $SNAP/share/themes
    default-provider: gtk-common-themes:gtk-3-themes
  icon-themes:
    interface: content
    target: $SNAP/share/icons
    default-provider: gtk-common-themes:icon-themes
  sound-themes:
    interface: content
    target: $SNAP/share/sounds
    default-provider: gtk-common-themes:sounds-themes

parts:
  add-ppa:
    plugin: nil
    override-pull: |
      echo "deb http://ppa.launchpad.net/martin-prazak/cgi-daily/ubuntu bionic main" | tee /etc/apt/sources.list.d/cgi-daily.list
      apt-key adv --keyserver keyserver.ubuntu.com --recv-keys AD1F7ADEA6EC2DD8E462467C210C13FD18B9423F
      apt update
      apt upgrade -yy

  desktop-qt5:
    source-type: git
    source: https://github.com/ubuntu/snapcraft-desktop-helpers
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
      - build-essential
      - qtbase5-dev
      - dpkg-dev
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5 # for loading icon themes which are svg
      - try: [appmenu-qt5] # not available on core18
      - locales-all
      - xdg-user-dirs
      - fcitx-frontend-qt5

  core:
    after: [add-ppa]
    plugin: cmake
    source: .
    configflags:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCONF_PATH='$SNAP/share/possumwood/possumwood.conf'
      - -DMAKE_CONF_FILE=OFF
    stage-packages:
      - libboost-filesystem1.65.1
      - libboost-serialization1.65.1
      - libboost-system1.65.1
      - libboost-regex1.65.1
      - libboost-thread1.65.1
      - libboost-test1.65.1
      - libboost-program-options1.65.1
      - libarmadillo8
      - libcharls1
      - libgdal20
      - libglew2.0
      - libglfw3
      - libglu1
      - libilmbase12
      - libluabind0.9.1v5
      - libogdi3.2
      - libopencolorio1v5
      - libopencv-core3.2
      - libopencv-imgcodecs3.2
      - libopencv-imgproc3.2
      - libopencv-videoio3.2
      - libraw1394-11
      - libraw16
      - libtbb2
      - libusb-1.0-0
      - libxinerama1
      - libxrandr2
      - libopencv-daily
      - libopenimageio-daily
      - libcgal-daily

  config:
    plugin: nil
    after: [core]
    override-build: |
      printf 'EXAMPLES $SNAP/share/possumwood/examples\nTOOLBARS $SNAP/share/possumwood/toolbars\nPLUGINS $SNAP/lib/possumwood/plugins\n' > $SNAPCRAFT_STAGE/share/possumwood/possumwood.conf
      mkdir -p $SNAPCRAFT_PART_INSTALL/share/possumwood && cp -p $SNAPCRAFT_STAGE/share/possumwood/possumwood.conf $SNAPCRAFT_PART_INSTALL/share/possumwood
